### ISSUE TITLE
SpeechToText doenst work

### ISSUE THREAD

**Issue by pedroalefm** [pwcremin/react-native-bluemix#26]
Sometimes the console return this error
unable to transcode data stream audio/ogg -> audio/x-float-array 
sometimes this
Write error: ssl=0xa2bd0788: I/O error during system call, Broken pipe
 I've the permission to audio record in my android manifest.

**Comment by gabrielperales** [comment]
Hi @pedroalefm, I'm also trying to make this library work. Which versions of React Native and Watson sdk are you using? Are you running this code in iOS? or just in Android?

**Comment by pedroalefm** [comment]
Sorry if I am to late haha. 
So, I already resolved this issue by editing the lib in node_modules. It happens because of the language, I speak portuguese and the lib only work in English. I`ve edited the language to work in portuguese. If you need help to make this lib work, I`m here. This saved a job with a client, but this need much more work to work well.

**Comment by evtuw** [comment]
@pedroalefm Can you help me? I'm from Vietnam and i'm using this lib, but it's don't support Vietnamese. Please help me resolve this issues. Thanks.
